### ISSUE TITLE
Provide an optional `--help` command line parameter to display config values

### ISSUE THREAD

**Issue by aphistic** [go-nacelle/nacelle#6]
Another suggestion from a code review with my team today was to provide the ability to give a `--help` command line switch that displays the environment variables, types, requirements, etc of all of the config values used in an application. They've used something like [github.com/urfave/cli](https://github.com/urfave/cli/) in the past mostly as a way to use the command line options as a way to show which environment variables are needed/available from the command line.

I think this is a good idea so you can have all that documentation available with the binary itself, but I'm also not sure how to implement it right now. I think it should be an opt-in feature provided by an option turned on in the bootstrapper, though, because I don't think that having that being taken over all the time is non-obvious.

Since configs are mostly loaded at `Init()` time, there's really no way to know which values are being used unless `config.Load()` is being called by something. I thought about a possible implementation being something that runs all the initializers and processes when `--help` is passed in, but only runs the `Init()` method on them and inspects the config afterward to see what was called, but people may be doing access to external services in their `Init()` methods so we can't assume that would always work.
The other idea I had was to have some sort of registration you could do of your config structs, but then it starts to get back into the way things used to work and I prefer the new method of active loading.

Any thoughts?

**Comment by efritz** [comment]
Yeah I've had this wish before too, actually.

What would you think of calling a global registration function (as a convention) at the time you define the struct? Kind of like how type check assignments work:

```go
type Config struct {
    // ...
}
config.Register(&Config{})
```

This would be able to catch mis-registrations though and would omit any options that could actually be used at runtime.

**Comment by aphistic** [comment]
I don't mind the idea of a global registration function, but I don't like that it would require using an `init()` function to do it. I think `init()` is a gross hack in most cases (it's global state taken to an extreme), so I don't like it being a recommended way to do things (see the cobra/viper docs for an example).

As I was typing this I thought about the v2 stuff and I'm on the fence about this idea, but what if we had this interface that could be applied to both a `Process` or an `Initializer`:
```go
type Registrar interface {
    Register(sc ServiceContainer) error
}

// Usage:
type config1 struct{
    Blah string `env:"BLAH"`
}
type config2 struct{
    Blah string `env:"BLAH"`
    Rawr int `env:"RAWR"`
}

type Process struct{}

func (p *Process) Register(sc ServiceContainer) error {
    if config, ok := sc.Get(ConfigKey).(Config); ok {
        config.Register(&config1{})
        config.Register(&config2{})
    }
}
```

This would provide something that can happen before `Init` is called that would allow a process/initializer to do any informing it needs to do and still keep it local to the process. It might only be used to register config info right now, but I made it a `ServiceContainer` parameter in case there's anything else that needs to be registered in the future.

If it makes it easier for users we could make it `Register(sc ServiceContainer, config Config) error` so they don't need to know how to get a config from a `ServiceContainer`, or even just `Register(config Config) error` (maybe `RegisterConfig(config Config) error`) if we don't want to leave it as wide open. Maybe the `error` doesn't need to exist on the `Register` method, either, if it signals to users that they shouldn't be doing any kind of calculations or processing in the method.

**Comment by efritz** [comment]
Yeah the idea of separating the config from the process a bit for a v2 release actually sounds good to me. I'll do a think/sleep iteration on this.

**Comment by efritz** [comment]
Trying to do this I ran into a little wall since we don't "register" any configuration structs today - we simply apply any tag modifiers supplied at the time of struct population, then populate that struct instance. We don't currently have an idiomatic recommendation for passing struct values around.

How does this feel?

```
type Process struct {
    config1 Config1
    config2 Config2
}

func (p *Process) Register(config Config) {
    config.Register(&p.config1{}) // populate struct (errors registered in config pkg)
    config.Register(&p.config2{}, displayTagSetter, fileTagPrefixer, etc...)
}

func (p *Process) Init(ctx context.Context) error {
    // Called after nacelle checks for config validation (will treat validation errors as startup errors)
    // ...
}
```

**Comment by aphistic** [comment]
I like that idea. I think it allows someone to keep their config centralized and avoids any global `init()`. My biggest concern would be whether the "populate struct" you mention would include `PostLoad` stuff or only include parsing the struct tags? If it's only parsing struct tags I'm on board, I'd just want to avoid the possibility of a `--help` call actually trying to connect to a database or some other unintended side-effect if someone does that in their `PostLoad`.

**Comment by efritz** [comment]
That seems like a bad thing to put in a post load. Really that hook is made for custom validation that isn't supported by the config loader directly.

If we make that clear in the documentation would you be alright with it?

**Comment by aphistic** [comment]
I agree it shouldn't be done, but we don't really have control over how users use the tools they're given. I could see someone saying that connecting to a database or some other external dependency is part of how they validate the config is right. Is there a reason we couldn't do everything except config callbacks? If we're just using the register to be aware of all the configs being used then just parsing struct tags should be OK, right?

Edit: It would also avoid needing to put any errors in an external place because we would do the "runtime callback" before `Init` so we can just return an actual error.

**Comment by efritz** [comment]
I'll look deeper into the config repo to see if it's easy to break those stages into two parts. I think it's probably fine since it's not a hook that triggers other config behavior.
